<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>这是最热的10部电影</title>
</head>
<body>
<div id="container" >
	<div id="header" >
		<h1 style="margin:0 auto;">超级电影网</h1></div>
	<div id="table" style="margin:0 auto;display:table-cell;vertical-align: middle;">
		<table border=1>
			<tr>
				<th>TOP</th>
				<th>电影名</th>
				<th>导演</th>
				<th>主演</th>
				<th>类型</th>
				<th>语言</th>
				<th>上映年份</th>
			</tr>
			<tr>
				<td>Top1</td>
		        <td>肖申克的救赎</td>
		        <td>导演名</td>
		        <td>主演名</td>
		        <td>剧情</td>
		        <td>英语</td>
		        <td>年份</td>
		    </tr>
		    <tr>
				<td>Top2</td>
		        <td>肖申克的救赎</td>
		        <td>导演名</td>
		        <td>主演名</td>
		        <td>剧情</td>
		        <td>英语</td>
		        <td>年份</td>
		    </tr>
		    <tr>
				<td>Top3</td>
		        <td>肖申克的救赎</td>
		        <td>导演名</td>
		        <td>主演名</td>
		        <td>剧情</td>
		        <td>英语</td>
		        <td>年份</td>
		    </tr>
		    <tr>
				<td>Top4</td>
		        <td>肖申克的救赎</td>
		        <td>导演名</td>
		        <td>主演名</td>
		        <td>剧情</td>
		        <td>英语</td>
		        <td>年份</td>
		    </tr>
		    <tr>
				<td>Top5</td>
		        <td>肖申克的救赎</td>
		        <td>导演名</td>
		        <td>主演名</td>
		        <td>剧情</td>
		        <td>英语</td>
		        <td>年份</td>
		    </tr>
		    <tr>
				<td>Top6</td>
		        <td>肖申克的救赎</td>
		        <td>导演名</td>
		        <td>主演名</td>
		        <td>剧情</td>
		        <td>英语</td>
		        <td>年份</td>
		    </tr>
		    <tr>
				<td>Top7</td>
		        <td>肖申克的救赎</td>
		        <td>导演名</td>
		        <td>主演名</td>
		        <td>剧情</td>
		        <td>英语</td>
		        <td>年份</td>
		    </tr>
		    <tr>
				<td>Top8</td>
		        <td>肖申克的救赎</td>
		        <td>导演名</td>
		        <td>主演名</td>
		        <td>剧情</td>
		        <td>英语</td>
		        <td>年份</td>
		    </tr>
		    <tr>
				<td>Top9</td>
		        <td>肖申克的救赎</td>
		        <td>导演名</td>
		        <td>主演名</td>
		        <td>剧情</td>
		        <td>英语</td>
		        <td>年份</td>
		    </tr>
		    <tr>
				<td>Top10</td>
		        <td>肖申克的救赎</td>
		        <td>导演名</td>
		        <td>主演名</td>
		        <td>剧情</td>
		        <td>英语</td>
		        <td>年份</td>
		    </tr>
		</table></div>
	</div>
</body>
</html>